image: ubuntu:18.04

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
  # the following script is taken from https://docs.gitlab.com/ee/ci/ssh_keys/README.html
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts

Deploy Changed to Server:       # This job runs in the build stage, which runs first.
  stage: build 
  script:
	  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./themes/** $SSH_USER@$DEV_HOST:/home/ubuntu/app/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'dev'"
